import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Check, Sparkles, TrendingUp, Building2, BarChart3, ImageIcon, GraduationCap } from "lucide-react"
import { Header } from "@/components/header"

export default function PricingPage() {
  const tiers = [
    {
      name: "Starter",
      price: "$99",
      description: "Perfect for small businesses getting started with AI-powered advertising",
      features: [
        "AI ad generator",
        "10 campaigns per month",
        "Basic performance tracking",
        "Email support",
        "Campaign templates",
        "Social media integration",
      ],
      cta: "Start Free Trial",
      highlighted: false,
      icon: Sparkles,
    },
    {
      name: "Growth",
      price: "$299",
      description: "For growing businesses ready to scale their advertising efforts",
      features: [
        "Everything in Starter",
        "Unlimited ad campaigns",
        "Performance optimization",
        "Audience segmentation",
        "Advanced analytics",
        "Priority support",
        "A/B testing tools",
        "Custom branding",
      ],
      cta: "Start Free Trial",
      highlighted: true,
      icon: TrendingUp,
    },
    {
      name: "Enterprise",
      price: "Custom",
      description: "Tailored solutions for multi-location wellness chains and large organizations",
      features: [
        "Everything in Growth",
        "Unlimited team members",
        "Dedicated account manager",
        "Custom integrations",
        "White-label options",
        "SLA guarantees",
        "Training & onboarding",
        "API access",
      ],
      cta: "Contact Sales",
      highlighted: false,
      icon: Building2,
    },
  ]

  const addOns = [
    {
      name: "Campaign Analytics Dashboard",
      description: "Advanced performance dashboards with real-time insights and custom reporting",
      price: "$49/month",
      icon: BarChart3,
    },
    {
      name: "AI-Generated Visuals",
      description: "Professional ad creatives and visuals generated by AI for your campaigns",
      price: "$79/month",
      icon: ImageIcon,
    },
    {
      name: "Marketing Workshops",
      description: "Expert-led workshops on branding, storytelling, and AI marketing literacy",
      price: "Starting at $499",
      icon: GraduationCap,
    },
  ]

  return (
    <main className="min-h-screen bg-background">
      <Header />

      {/* Hero Section */}
      <section className="border-b border-border bg-gradient-to-b from-primary/5 to-background py-20">
        <div className="container mx-auto px-4 text-center">
          <h1 className="mb-4 text-balance text-4xl font-bold tracking-tight md:text-5xl lg:text-6xl">
            Simple, Transparent Pricing
          </h1>
          <p className="mx-auto mb-8 max-w-2xl text-pretty text-lg text-muted-foreground md:text-xl">
            Choose the perfect plan for your business. All plans include our AI-powered ad generation technology to help
            you compete with the big brands.
          </p>
          <div className="flex items-center justify-center gap-2 text-sm text-muted-foreground">
            <Check className="h-4 w-4 text-primary" />
            <span>14-day free trial</span>
            <span className="mx-2">•</span>
            <Check className="h-4 w-4 text-primary" />
            <span>No credit card required</span>
            <span className="mx-2">•</span>
            <Check className="h-4 w-4 text-primary" />
            <span>Cancel anytime</span>
          </div>
        </div>
      </section>

      {/* Pricing Tiers */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
            {tiers.map((tier) => {
              const Icon = tier.icon
              return (
                <Card
                  key={tier.name}
                  className={`relative flex flex-col ${
                    tier.highlighted ? "border-primary shadow-lg ring-2 ring-primary/20" : ""
                  }`}
                >
                  {tier.highlighted && (
                    <div className="absolute -top-4 left-1/2 -translate-x-1/2 rounded-full bg-primary px-4 py-1 text-sm font-medium text-primary-foreground">
                      Most Popular
                    </div>
                  )}
                  <CardHeader>
                    <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10">
                      <Icon className="h-6 w-6 text-primary" />
                    </div>
                    <CardTitle className="text-2xl">{tier.name}</CardTitle>
                    <CardDescription className="text-pretty">{tier.description}</CardDescription>
                    <div className="mt-4">
                      <span className="text-4xl font-bold">{tier.price}</span>
                      {tier.price !== "Custom" && <span className="text-muted-foreground">/month</span>}
                    </div>
                  </CardHeader>
                  <CardContent className="flex-1">
                    <ul className="space-y-3">
                      {tier.features.map((feature) => (
                        <li key={feature} className="flex items-start gap-3">
                          <Check className="mt-0.5 h-5 w-5 shrink-0 text-primary" />
                          <span className="text-sm">{feature}</span>
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                  <CardFooter>
                    <Button asChild className="w-full" variant={tier.highlighted ? "default" : "outline"} size="lg">
                      <Link href={tier.name === "Enterprise" ? "#contact" : "/auth/sign-up"}>{tier.cta}</Link>
                    </Button>
                  </CardFooter>
                </Card>
              )
            })}
          </div>
        </div>
      </section>

      {/* Add-Ons Section */}
      <section className="border-t border-border bg-muted/30 py-20">
        <div className="container mx-auto px-4">
          <div className="mb-12 text-center">
            <h2 className="mb-4 text-balance text-3xl font-bold tracking-tight md:text-4xl">Enhance Your Experience</h2>
            <p className="mx-auto max-w-2xl text-pretty text-lg text-muted-foreground">
              Take your advertising to the next level with our premium add-ons and services
            </p>
          </div>

          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {addOns.map((addOn) => {
              const Icon = addOn.icon
              return (
                <Card key={addOn.name} className="flex flex-col">
                  <CardHeader>
                    <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10">
                      <Icon className="h-6 w-6 text-primary" />
                    </div>
                    <CardTitle className="text-xl">{addOn.name}</CardTitle>
                    <CardDescription className="text-pretty">{addOn.description}</CardDescription>
                  </CardHeader>
                  <CardContent className="flex-1">
                    <p className="text-2xl font-bold">{addOn.price}</p>
                  </CardContent>
                  <CardFooter>
                    <Button asChild variant="outline" className="w-full bg-transparent">
                      <Link href="#contact">Learn More</Link>
                    </Button>
                  </CardFooter>
                </Card>
              )
            })}
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <div className="mb-12 text-center">
            <h2 className="mb-4 text-balance text-3xl font-bold tracking-tight md:text-4xl">
              Frequently Asked Questions
            </h2>
          </div>

          <div className="mx-auto max-w-3xl space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Can I change plans later?</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">
                  Yes! You can upgrade or downgrade your plan at any time. Changes take effect at the start of your next
                  billing cycle.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="text-lg">What payment methods do you accept?</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">
                  We accept all major credit cards (Visa, Mastercard, American Express) and ACH transfers for Enterprise
                  customers.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Is there a setup fee?</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">
                  No setup fees for Starter and Growth plans. Enterprise plans may include a one-time onboarding fee
                  depending on customization requirements.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="text-lg">What happens after my trial ends?</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">
                  After your 14-day free trial, you'll be automatically enrolled in the plan you selected. You can
                  cancel anytime before the trial ends with no charges.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="border-t border-border bg-primary/5 py-20">
        <div className="container mx-auto px-4 text-center">
          <h2 className="mb-4 text-balance text-3xl font-bold tracking-tight md:text-4xl">
            Ready to Transform Your Advertising?
          </h2>
          <p className="mx-auto mb-8 max-w-2xl text-pretty text-lg text-muted-foreground">
            Join thousands of small businesses using AWE to create professional, effective ads that compete with the big
            brands.
          </p>
          <div className="flex flex-col items-center justify-center gap-4 sm:flex-row">
            <Button asChild size="lg" className="min-w-[200px]">
              <Link href="/auth/sign-up">Start Free Trial</Link>
            </Button>
            <Button asChild variant="outline" size="lg" className="min-w-[200px] bg-transparent">
              <Link href="#contact">Contact Sales</Link>
            </Button>
          </div>
        </div>
      </section>
    </main>
  )
}
